# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d35d411b23a762a462ebdd08683a1115c7a21e3b27805ca96e26a6b06aaaf18792bf2de204d41170ef3dfe1f47f736a72f2cf19b793f50e4e9d0c509c195fd93

test:
  secret_key_base: 69142994e203c2998ca766259deb82341f35e6b01c27ee03b5653a264a9e0413f0c21b9cffbdd78a9a02acab5fb7c33e0528accf66fd3bce1e854f57a7624800

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
